version: '2.1'

services:
  # This is the service that will run on your device
  weather-display:
    # This tells Balena to build the Dockerfile in the current directory
    build: .
    privileged: true
    # These are the environment variables that will be set in the container
    environment:
      - 'TZ=Europe/London'
      - 'departureStation=PAD'
      - 'outOfHoursName=London Paddington'
      - 'refreshTime=120'
      - 'apiKey=e78989d4-8055-4766-80cb-fc95055a9802'
      - 'operatingHours=8-24'
      - 'screenBlankHours=1-6'
      - 'screenRotation=0'
      - 'dualScreen=False'
      - 'destinationStation='
      - 'timeOffset=0'
      - 'screen1Platform='
      - 'screen2Platform='
      - 'individualStationDepartureTime=False'
      - 'showDepartureNumbers=False'
      - 'firstDepartureBold=True'
      - 'targetFPS=70'
      - 'fpsTime=10'
      - 'debug=False'
      - 'debugDate=2025-09-01T12:00:00'
      - 'location=Harpenden'
      - 'otherLocation=London'
      - 'openWeatherApiKey=2b94722d16f4849f6b8a5528bbac4933'